package LN.entity;
// Generated 03/07/2011 16:02:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private int codcliente;
     private String razaosocial;
     private String fanatasia;
     private String nomecontato;
     private String endereco;
     private String bairro;
     private String cep;
     private String cidade;
     private String telefone;
     private String celular;
     private Date datanascimento;
     private String rg;
     private String cpf;
     private String cnpj;
     private String inscricaoestadual;
     private String observacao;
     private Date datacadastro;
     private Set orcamentoses = new HashSet(0);

    public Clientes() {
    }

     public Clientes(int codcliente) {
        this.codcliente = codcliente;
        this.razaosocial = razaosocial;
    }
	
    public Clientes(int codcliente, String razaosocial) {
        this.codcliente = codcliente;
        this.razaosocial = razaosocial;
    }
    public Clientes(int codcliente, String razaosocial, String fanatasia, String nomecontato, String endereco, String bairro, String cep, String cidade, String telefone, String celular, Date datanascimento, String rg, String cpf, String cnpj, String inscricaoestadual, String observacao, Date datacadastro){//, Set orcamentoses) {
       this.codcliente = codcliente;
       this.razaosocial = razaosocial;
       this.fanatasia = fanatasia;
       this.nomecontato = nomecontato;
       this.endereco = endereco;
       this.bairro = bairro;
       this.cep = cep;
       this.cidade = cidade;
       this.telefone = telefone;
       this.celular = celular;
       this.datanascimento = datanascimento;
       this.rg = rg;
       this.cpf = cpf;
       this.cnpj = cnpj;
       this.inscricaoestadual = inscricaoestadual;
       this.observacao = observacao;
       this.datacadastro = datacadastro;
       this.orcamentoses = orcamentoses;
    }

   
    public int getCodcliente() {
        return this.codcliente;
    }
    
    public void setCodcliente(int codcliente) {
        this.codcliente = codcliente;
    }
    public String getRazaosocial() {
        return this.razaosocial;
    }
    
    public void setRazaosocial(String razaosocial) {
        this.razaosocial = razaosocial;
    }
    public String getFanatasia() {
        return this.fanatasia;
    }
    
    public void setFanatasia(String fanatasia) {
        this.fanatasia = fanatasia;
    }
    public String getNomecontato() {
        return this.nomecontato;
    }
    
    public void setNomecontato(String nomecontato) {
        this.nomecontato = nomecontato;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public Date getDatanascimento() {
        return this.datanascimento;
    }
    
    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getInscricaoestadual() {
        return this.inscricaoestadual;
    }
    
    public void setInscricaoestadual(String inscricaoestadual) {
        this.inscricaoestadual = inscricaoestadual;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Date getDatacadastro() {
        return this.datacadastro;
    }
    
    public void setDatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }
    public Set getOrcamentoses() {
        return this.orcamentoses;
    }
    
    public void setOrcamentoses(Set orcamentoses) {
        this.orcamentoses = orcamentoses;
    }




}


