package LN.entity;
// Generated 03/07/2011 16:02:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Fornecedores generated by hbm2java
 */
public class Fornecedores  implements java.io.Serializable {


     private int codfornecedor;
     private String fornecedor;
     private String endereco;
     private String bairro;
     private String cep;
     private String cidade;
     private String vendedor;
     private String email;
     private String telefone;
     private String celular;
     private String telefonevendedor;
     private String cnpj;
     private String observacao;
     private Date datacadastro;

    public Fornecedores() {
    }

	
    public Fornecedores(int codfornecedor, String fornecedor) {
        this.codfornecedor = codfornecedor;
        this.fornecedor = fornecedor;
    }
    public Fornecedores(int codfornecedor, String fornecedor, String endereco, String bairro, String cep, String cidade, String vendedor, String email, String telefone, String celular, String telefonevendedor, String cnpj, String observacao, Date datacadastro) {
       this.codfornecedor = codfornecedor;
       this.fornecedor = fornecedor;
       this.endereco = endereco;
       this.bairro = bairro;
       this.cep = cep;
       this.cidade = cidade;
       this.vendedor = vendedor;
       this.email = email;
       this.telefone = telefone;
       this.celular = celular;
       this.telefonevendedor = telefonevendedor;
       this.cnpj = cnpj;
       this.observacao = observacao;
       this.datacadastro = datacadastro;
    }
   
    public int getCodfornecedor() {
        return this.codfornecedor;
    }
    
    public void setCodfornecedor(int codfornecedor) {
        this.codfornecedor = codfornecedor;
    }
    public String getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(String fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(String vendedor) {
        this.vendedor = vendedor;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getTelefonevendedor() {
        return this.telefonevendedor;
    }
    
    public void setTelefonevendedor(String telefonevendedor) {
        this.telefonevendedor = telefonevendedor;
    }
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Date getDatacadastro() {
        return this.datacadastro;
    }
    
    public void setDatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }




}


