package LN.entity;
// Generated 03/07/2011 16:02:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Materiais generated by hbm2java
 */
public class Materiais  implements java.io.Serializable {


     private String codmateriais;
     private String descricao;
     private Integer qtdestoque;
     private Integer qtdminima;
     private Double valor;
     private String fornecedor;
     private Date datacadastro;
     private String unidade;

    public Materiais() {
    }

	
    public Materiais(String codmateriais) {
        this.codmateriais = codmateriais;
    }
    public Materiais(String codmateriais, String descricao, String unidade,Integer qtdestoque, Integer qtdminima, Double valor, String fornecedor, Date datacadastro) {
       this.codmateriais = codmateriais;
       this.descricao = descricao;
       this.qtdestoque = qtdestoque;
       this.qtdminima = qtdminima;
       this.valor = valor;
       this.fornecedor = fornecedor;
       this.datacadastro = datacadastro;
       this.unidade = unidade;
    }
   
    public String getCodmateriais() {
        return this.codmateriais;
    }
    
    public void setCodmateriais(String codmateriais) {
        this.codmateriais = codmateriais;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Integer getQtdestoque() {
        return this.qtdestoque;
    }
    
    public void setQtdestoque(Integer qtdestoque) {
        this.qtdestoque = qtdestoque;
    }
    public Integer getQtdminima() {
        return this.qtdminima;
    }
    
    public void setQtdminima(Integer qtdminima) {
        this.qtdminima = qtdminima;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public String getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(String fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Date getDatacadastro() {
        return this.datacadastro;
    }
    
    public void setDatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }
    public String getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(String unidade) {
        this.unidade = unidade;
    }




}


