package LN.entity;
// Generated 03/07/2011 16:02:55 by Hibernate Tools 3.2.1.GA



/**
 * MateriaisOrcamentos generated by hbm2java
 */
public class MateriaisOrcamentos  implements java.io.Serializable {


     private int codmateriais;
     private Orcamentos orcamentos;
     private Integer quantidade;
     private String unidade;
     private String produto;
     private Double valorunitario;
     private Double valortotal;
     private Integer item;

    public MateriaisOrcamentos() {
    }

	
    public MateriaisOrcamentos(int codmateriais) {
        this.codmateriais = codmateriais;
    }
    public MateriaisOrcamentos(int codmateriais, Orcamentos orcamentos, Integer quantidade, String unidade, String produto, Double valorunitario, Double valortotal, Integer item) {
       this.codmateriais = codmateriais;
       this.orcamentos = orcamentos;
       this.quantidade = quantidade;
       this.unidade = unidade;
       this.produto = produto;
       this.valorunitario = valorunitario;
       this.valortotal = valortotal;
       this.item = item;
    }
   
    public int getCodmateriais() {
        return this.codmateriais;
    }
    
    public void setCodmateriais(int codmateriais) {
        this.codmateriais = codmateriais;
    }
    public Orcamentos getOrcamentos() {
        return this.orcamentos;
    }
    
    public void setOrcamentos(Orcamentos orcamentos) {
        this.orcamentos = orcamentos;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public String getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(String unidade) {
        this.unidade = unidade;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public Double getValorunitario() {
        return this.valorunitario;
    }
    
    public void setValorunitario(Double valorunitario) {
        this.valorunitario = valorunitario;
    }
    public Double getValortotal() {
        return this.valortotal;
    }
    
    public void setValortotal(Double valortotal) {
        this.valortotal = valortotal;
    }
    public Integer getItem() {
        return this.item;
    }
    
    public void setItem(Integer item) {
        this.item = item;
    }




}


