package LN.entity;
// Generated 03/07/2011 16:02:55 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orcamentos generated by hbm2java
 */
public class Orcamentos  implements java.io.Serializable {


     private String codorcamentos;
     private Clientes clientes;
     private String cliente;
     private String ac;
     private String unidade;
     private String solicitante;
     private String referente;
     private String observacoes;
     private String status;
     private Date datacadastro;
     private String local;
     private String pedido;
     private String descricao;
     private String prazoentrega;
     private String condicoespagamento;
     private String validadeproposta;
     private Set materiaisOrcamentoses = new HashSet(0);

    public Orcamentos() {
    }

	
    public Orcamentos(String codorcamentos) {
        this.codorcamentos = codorcamentos;
    }
    //public Orcamentos(String codorcamentos, Clientes clientes, String cliente, String ac, String unidade, String solicitante, String referente, String observacoes, String status, Date datacadastro, String local, String pedido, String descricao, String prazoentrega, String condicoespagamento, String validadeproposta){//, Set materiaisOrcamentoses) {
    public Orcamentos(String codorcamentos, Clientes clientes, String cliente, String ac, String unidade, String solicitante, String referente, String observacoes, String status, Date datacadastro, String local, String pedido, String descricao, String prazoEntrega, String condicoesPagamento, String validadeProposta){//, Set materiaisOrcamentoses) {
        this.codorcamentos = codorcamentos;
       this.clientes = clientes;
       this.cliente = cliente;
       this.ac = ac;
       this.unidade = unidade;
       this.solicitante = solicitante;
       this.referente = referente;
       this.observacoes = observacoes;
       this.status = status;
       this.datacadastro = datacadastro;
       this.local = local;
       this.pedido = pedido;
       this.descricao = descricao;
       this.prazoentrega = prazoentrega;
       this.condicoespagamento = condicoespagamento;
       this.validadeproposta = validadeproposta;
       this.materiaisOrcamentoses = materiaisOrcamentoses;
    }
   
    public String getCodorcamentos() {
        return this.codorcamentos;
    }
    
    public void setCodorcamentos(String codorcamentos) {
        this.codorcamentos = codorcamentos;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getAc() {
        return this.ac;
    }
    
    public void setAc(String ac) {
        this.ac = ac;
    }
    public String getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(String unidade) {
        this.unidade = unidade;
    }
    public String getSolicitante() {
        return this.solicitante;
    }
    
    public void setSolicitante(String solicitante) {
        this.solicitante = solicitante;
    }
    public String getReferente() {
        return this.referente;
    }
    
    public void setReferente(String referente) {
        this.referente = referente;
    }
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getDatacadastro() {
        return this.datacadastro;
    }
    
    public void setDatacadastro(Date datacadastro) {
        this.datacadastro = datacadastro;
    }
    public String getLocal() {
        return this.local;
    }
    
    public void setLocal(String local) {
        this.local = local;
    }
    public String getPedido() {
        return this.pedido;
    }
    
    public void setPedido(String pedido) {
        this.pedido = pedido;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getPrazoentrega() {
        return this.prazoentrega;
    }
    
    public void setPrazoentrega(String prazoentrega) {
        this.prazoentrega = prazoentrega;
    }
    public String getCondicoespagamento() {
        return this.condicoespagamento;
    }
    
    public void setCondicoespagamento(String condicoespagamento) {
        this.condicoespagamento = condicoespagamento;
    }
    public String getValidadeproposta() {
        return this.validadeproposta;
    }
    
    public void setValidadeproposta(String validadeproposta) {
        this.validadeproposta = validadeproposta;
    }
    public Set getMateriaisOrcamentoses() {
        return this.materiaisOrcamentoses;
    }
    
    public void setMateriaisOrcamentoses(Set materiaisOrcamentoses) {
        this.materiaisOrcamentoses = materiaisOrcamentoses;
    }




}


