package LN.entity;
// Generated 03/07/2011 16:02:55 by Hibernate Tools 3.2.1.GA



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String codusuario;
     private String nome;
     private String senha;
     private String checkprodutos;
     private String checkclientes;
     private String checkfornecedores;
     private String checkorcamentos;
     private String checkrelatorios;
     private String checkentradasaida;
     private String checkusuarios;

    public Usuarios() {
    }

	
    public Usuarios(String codusuario) {
        this.codusuario = codusuario;
    }
    public Usuarios(String codusuario, String nome, String senha, String checkprodutos, String checkclientes, String checkfornecedores, String checkorcamentos, String checkrelatorios, String checkentradasaida, String checkusuarios) {
       this.codusuario = codusuario;
       this.nome = nome;
       this.senha = senha;
       this.checkprodutos = checkprodutos;
       this.checkclientes = checkclientes;
       this.checkfornecedores = checkfornecedores;
       this.checkorcamentos = checkorcamentos;
       this.checkrelatorios = checkrelatorios;
       this.checkentradasaida = checkentradasaida;
       this.checkusuarios = checkusuarios;
    }
   
    public String getCodusuario() {
        return this.codusuario;
    }
    
    public void setCodusuario(String codusuario) {
        this.codusuario = codusuario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getCheckprodutos() {
        return this.checkprodutos;
    }
    
    public void setCheckprodutos(String checkprodutos) {
        this.checkprodutos = checkprodutos;
    }
    public String getCheckclientes() {
        return this.checkclientes;
    }
    
    public void setCheckclientes(String checkclientes) {
        this.checkclientes = checkclientes;
    }
    public String getCheckfornecedores() {
        return this.checkfornecedores;
    }
    
    public void setCheckfornecedores(String checkfornecedores) {
        this.checkfornecedores = checkfornecedores;
    }
    public String getCheckorcamentos() {
        return this.checkorcamentos;
    }
    
    public void setCheckorcamentos(String checkorcamentos) {
        this.checkorcamentos = checkorcamentos;
    }
    public String getCheckrelatorios() {
        return this.checkrelatorios;
    }
    
    public void setCheckrelatorios(String checkrelatorios) {
        this.checkrelatorios = checkrelatorios;
    }
    public String getCheckentradasaida() {
        return this.checkentradasaida;
    }
    
    public void setCheckentradasaida(String checkentradasaida) {
        this.checkentradasaida = checkentradasaida;
    }
    public String getCheckusuarios() {
        return this.checkusuarios;
    }
    
    public void setCheckusuarios(String checkusuarios) {
        this.checkusuarios = checkusuarios;
    }




}


