/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadClientes.java
 *
 * Created on 07/05/2011, 17:30:00
 */

package Tela;

import LN.entity.Clientes;
import LN.entity.Fornecedores;
import Util.HibernateUtil;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;
import org.hibernate.Query;
import org.hibernate.SQLQuery;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 *
 * @author Leonardo
 */
public class CadFornecedores extends javax.swing.JInternalFrame {

    private static CadFornecedores cadFornecedores;
    private Inicial inicial = null;
    private SessionFactory fabricaDeSessoes;
    private int codigoCliente;

    /** Creates new form CadClientes */
    public CadFornecedores(Inicial inicial) {
        initComponents();

        setFrameIcon(new ImageIcon(this.getClass().getClassLoader().getResource("imagens/IconeLN.png")));

        SimpleDateFormat sfd = new SimpleDateFormat("dd/MM/yyyy");
        String dataBusca = sfd.format(new Date());

        Campos(false);
        LimpaCampos();

        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jTextFieldPesqFornecedor.setEditable(false);
        jTextFieldPesqVendedor.setEditable(false);

    Dimension centraliza = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((centraliza.width-this.getSize().width)/2,
                      (centraliza.height-this.getSize().height)/2-30);

        //jTextFieldNOrcamentoBusca.requestFocus();

    }

    public static CadFornecedores getInstance(Inicial instancia) throws PropertyVetoException, SQLException, ClassNotFoundException {
        if(cadFornecedores == null)
            cadFornecedores = new CadFornecedores(instancia);
        return cadFornecedores;
    }

    public void Campos( boolean x){
        Component[] c = jPanelCliente.getComponents();
        for(int j = 0; j < c.length; j++) {
           if(c[j] instanceof JTextComponent) {
              JTextComponent cmp = (JTextComponent)c[j];
              cmp.setEditable(x);

          }
        }
    }

    public void LimpaCampos(){
        Component[] c = jPanelCliente.getComponents();
        for(int j = 0; j < c.length; j++) {
           if(c[j] instanceof JTextComponent) {
              JTextComponent cmp = (JTextComponent)c[j];
              cmp.setText("");
              //DefaultTableModel  dtm =(DefaultTableModel)jTableHistoricoOrcamento.getModel();
              //dtm.setRowCount(0);
              jTextFieldDataCadastro.setText("");
              jTextFieldRazaoSocial.requestFocus();
              jLabelRetorno.setText("");
          }
        }
    }

    public static String getDataTelaToBD(String x) {
        java.lang.String dia, mes, ano = "";
        java.lang.String data = "";
        dia = x.substring(0,2);
       //System.out.println("DIA " + dia);
        mes = x.substring(3,5);
        ano = x.substring(6, 10);
        data = mes +"/"+ dia + "/" + ano;
        //System.out.println("D  " + data );
        return data;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextFieldTelVendedor = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCNPJ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldInscricaoEstadual = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldVendedor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldObservacao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPesqFornecedor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldPesqVendedor = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelRetorno = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de fornecedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Fornecedor:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Bairro:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("CEP:");

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Telefone:");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel8.setText("Celular:");

        try {
            jFormattedTextFieldCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Tel Vendedor:");

        try {
            jFormattedTextFieldTelVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Email:");

        jLabel12.setText("CNPJ:");

        jLabel13.setText("Inscrição estadual:");

        jLabel14.setText("Vendedor:");

        jLabel15.setText("Observação:");

        jLabel18.setText("Data cadastro:");

        jTextFieldDataCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel19.setText("Código:");

        jTextFieldCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanelClienteLayout = new javax.swing.GroupLayout(jPanelCliente);
        jPanelCliente.setLayout(jPanelClienteLayout);
        jPanelClienteLayout.setHorizontalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTelVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldObservacao, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldInscricaoEstadual))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelClienteLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelClienteLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                            .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                    .addGroup(jPanelClienteLayout.createSequentialGroup()
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelClienteLayout.setVerticalGroup(
            jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClienteLayout.createSequentialGroup()
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldObservacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonNovo.setMnemonic('N');
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setMnemonic('S');
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setMnemonic('A');
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonDeletar.setMnemonic('D');
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonSair.setMnemonic('R');
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel16.setText("Fornecedor:");

        jTextFieldPesqFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesqFornecedorKeyReleased(evt);
            }
        });

        jLabel17.setText("Vendedor:");

        jTextFieldPesqVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesqVendedorKeyReleased(evt);
            }
        });

        jButtonPesquisar.setMnemonic('P');
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesqFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPesqVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldPesqFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldPesqVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelRetorno.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRetorno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonSalvar)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonDeletar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSair))
                            .addComponent(jPanelCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabelRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonDeletar)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        try{
            if(jButtonNovo.getText().equals("Cancelar")){
               jButtonNovo.setText("Novo");
               jButtonSalvar.setEnabled(false);
               Campos(false);
               LimpaCampos();
            }else{
               Campos(true);
               jButtonNovo.setText("Cancelar");
               jButtonAlterar.setEnabled(false);
               jButtonDeletar.setEnabled(false);
               jButtonSalvar.setEnabled(true);

                Session sessao = HibernateUtil.getSessionFactory().openSession();
                Transaction transacao = sessao.beginTransaction();

                SQLQuery query = sessao.createSQLQuery("select nextval('seq_fornecedor')");
                Object object = query.uniqueResult();
                System.out.println("NEXTVAL NOVO FORNECEDOR "+( (java.math.BigInteger)object ).longValue());
                codigoCliente = (int) ((java.math.BigInteger)object).longValue();
                LimpaCampos();
                transacao.commit();
                sessao.close();
                jTextFieldCodigo.setText(((java.math.BigInteger)object ).toString());

                SimpleDateFormat sfd = new SimpleDateFormat("dd/MM/yyyy");
                String data = sfd.format(new Date());

                jTextFieldDataCadastro.setText(data);

                //
            }
       }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro: "+ ex+"\n Causa: "+ ex.getCause(), "Atenção - Novo", JOptionPane.INFORMATION_MESSAGE );
       }
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try{

            String razaoSocial, fantasia, vendedor, endereco, bairro, cidade, cep,
               telefone, celular, telefoneVendedor, dataNascimento, email, cnpj, inscricaoEstadual,
               dataCadastro, observacao;

            int codigo = Integer.valueOf(jTextFieldCodigo.getText());
            razaoSocial = jTextFieldRazaoSocial.getText();
            //fantasia =jTextFieldFantasia.getText().toUpperCase();
            vendedor = jTextFieldVendedor.getText();
            endereco = jTextFieldEndereco.getText();
            bairro = jTextFieldBairro.getText();
            cidade = jTextFieldCidade.getText();
            cep = jFormattedTextFieldCep.getText();
            telefone = jFormattedTextFieldTelefone.getText();
            celular = jFormattedTextFieldCelular.getText();
            telefoneVendedor = jFormattedTextFieldTelVendedor.getText();
            email = jTextFieldEmail.getText();
            //cpf = jFormattedTextFieldCPF.getText().toUpperCase();
            cnpj = jTextFieldCNPJ.getText();
            //inscricaoEstadual = jTextFieldInscricaoEstadual.getText().toUpperCase();
            observacao = jTextFieldObservacao.getText();
            dataCadastro = jTextFieldDataCadastro.getText();

            Session sessao = HibernateUtil.getSessionFactory().openSession();
            Transaction transacao = sessao.beginTransaction();

            Fornecedores fornecedores = new Fornecedores (   codigo,               razaoSocial,       endereco,        bairro,        cep,        cidade,        vendedor,        email,         telefone,        celular,        telefoneVendedor,        cnpj,        observacao, new Date(getDataTelaToBD(dataCadastro)));

           sessao.save(fornecedores);
           transacao.commit();
           sessao.close();

           LimpaCampos();
           Campos(false);
           if(jButtonNovo.getText().equals("Cancelar")){
               jButtonNovo.setText("Novo");
               jButtonSalvar.setEnabled(false);
               JOptionPane.showMessageDialog(null, "Fornecedor incluído com sucesso");
           }
       }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro: "+ ex+"\n Causa: "+ ex.getCause(), "Atenção - Salvando", JOptionPane.INFORMATION_MESSAGE );
       }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
    try{

           Session sessao = HibernateUtil.getSessionFactory().openSession();
           Transaction transacao = sessao.beginTransaction();

           if(jTextFieldCodigo.getText().equals("") ){
               JOptionPane.showMessageDialog(null,"Pesquise algum fornecedor para deletar", "Atenção", JOptionPane.INFORMATION_MESSAGE );
               return;
           }else{
               Object[] options = { "Sim", "Não" };
              int a = JOptionPane.showOptionDialog(this, "Deseja realmente apagar este fornecedor?","Atenção",
                  JOptionPane.YES_NO_OPTION ,JOptionPane.QUESTION_MESSAGE, null,
                  options, options[0]);
              if(a == JOptionPane.YES_OPTION){
                   Fornecedores fornecedores = (Fornecedores) sessao.load(Fornecedores.class,Integer.parseInt(jTextFieldCodigo.getText()));
                   //System.out.println("DATA "+ new Date("dd/MM/yyyy"));
                   sessao.delete(fornecedores);
                   sessao.flush();
                   transacao.commit();
                   sessao.close();

                   LimpaCampos();
                   JOptionPane.showMessageDialog(null, "Fornecedor "+jTextFieldCodigo.getText()+" deletado com sucesso");

                  System.out.println("Fornecedor <html><b>"+jTextFieldCodigo.getText()+"</b></html> deletado com sucesso!");
               }else{
                  System.out.println("clicou em NÂO");
                  return;
               }
           }
       }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro: "+ ex+"\n Causa: "+ ex.getCause(), "Atenção - Deletando", JOptionPane.INFORMATION_MESSAGE );
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        try{

            if(jButtonAlterar.getLabel().equals("Atualizar")){
                jButtonAlterar.setLabel("Alterar");
                Campos(false);
                System.out.println("ATUALIZANDO FORNECEDOR");


                String razaoSocial, fantasia, vendedor, endereco, bairro, cidade, cep,
                   telefone, celular, telefoneVendedor, dataNascimento, email, cnpj, inscricaoEstadual,
                   dataCadastro, observacao;

                int codigo = Integer.valueOf(jTextFieldCodigo.getText());
                razaoSocial = jTextFieldRazaoSocial.getText();
                //fantasia =jTextFieldFantasia.getText().toUpperCase();
                vendedor = jTextFieldVendedor.getText();
                endereco = jTextFieldEndereco.getText();
                bairro = jTextFieldBairro.getText();
                cidade = jTextFieldCidade.getText();
                cep = jFormattedTextFieldCep.getText();
                telefone = jFormattedTextFieldTelefone.getText();
                celular = jFormattedTextFieldCelular.getText();
                telefoneVendedor = jFormattedTextFieldTelVendedor.getText();
                email = jTextFieldEmail.getText();
                //cpf = jFormattedTextFieldCPF.getText().toUpperCase();
                cnpj = jTextFieldCNPJ.getText();
                //inscricaoEstadual = jTextFieldInscricaoEstadual.getText().toUpperCase();
                observacao = jTextFieldObservacao.getText();
                dataCadastro = jTextFieldDataCadastro.getText();

                Session sessao = HibernateUtil.getSessionFactory().openSession();
                Transaction transacao = sessao.beginTransaction();

                Fornecedores fornecedores = new Fornecedores (   codigo,               razaoSocial,       endereco,        bairro,        cep,        cidade,        vendedor,        email,         telefone,        celular,        telefoneVendedor,        cnpj,        observacao, new Date(getDataTelaToBD(dataCadastro)));
                                              //Fornecedores(int codfornecedor, String fornecedor, String endereco, String bairro, String cep, String cidade, String vendedor, String email, String telefone, String celular, String telefonevendedor, String cnpj, String observacao, Date datacadastro);
                sessao.update(fornecedores);
                transacao.commit();
                sessao.close();

                Campos(false);
                System.out.println("COMMIT UPDATE");
                JOptionPane.showMessageDialog(null, "Fornecedor atualizado com sucesso");
           }else{
                jButtonAlterar.setText("Atualizar");
                Campos(true);
                jTextFieldCodigo.setEditable(false);
           }
       }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro: "+ ex+"\n Causa: "+ ex.getCause(), "Atenção - Atualizando", JOptionPane.INFORMATION_MESSAGE );
        }

    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jTextFieldPesqFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesqFornecedorKeyReleased
            SimpleDateFormat sfd = new SimpleDateFormat("dd/MM/yyyy");
            String data = sfd.format(new Date());

            Session sessao = HibernateUtil.getSessionFactory().openSession();
            Transaction transacao = sessao.beginTransaction();
            //Query consultaOrca = sessao.createQuery("from Orcamentos as o where o.codorcamentos = '"+jListOrcamento.getSelectedValue().toString()+"' ");

            Query queryFornecedores = sessao.createQuery("from Fornecedores as f where f.fornecedor like '"+jTextFieldPesqFornecedor.getText().toUpperCase()+"%' order by f.fornecedor");

            //Query consultaMat = sessao.createQuery("from MateriaisOrcamentos as mo where mo.codorcamentos = '"+jListOrcamento.getSelectedValue().toString()+"'");
            List listFornecedores = queryFornecedores.list();
            //List materiais = consultaMat.list();
            //System.out.println("foram encontradas "+orcamentos.size()+" orcamentos");
            Iterator i = listFornecedores.iterator();

            Fornecedores fornecedores = null;
           // javax.swing.table.DefaultTableModel tableResultado =(javax.swing.table.DefaultTableModel)jTableHistoricoOrcamento.getModel();
            //tableResultado.setRowCount(0);
            //MateriaisOrcamentos matOrca = new MateriaisOrcamentos();
            //System.out.println("MAT ->"+ matOrca.getProduto());
            if(jTextFieldPesqFornecedor.getText().equals("")){
                //Consulta = false;
                LimpaCampos();
                jTextFieldPesqFornecedor.requestFocus();
            }else{
                while (i.hasNext()) {

                     fornecedores = (Fornecedores) i.next();

                    jTextFieldCodigo.setText(String.valueOf(fornecedores.getCodfornecedor()));
                    jTextFieldRazaoSocial.setText(fornecedores.getFornecedor());
                    jTextFieldVendedor.setText(fornecedores.getVendedor());
                    jTextFieldEndereco.setText(fornecedores.getEndereco());
                    jTextFieldBairro.setText(fornecedores.getBairro());
                    jTextFieldCidade.setText(fornecedores.getCidade());
                    jFormattedTextFieldCep.setText(fornecedores.getCep());
                    jFormattedTextFieldTelefone.setText(fornecedores.getTelefone());
                    jFormattedTextFieldCelular.setText(fornecedores.getCelular());
                    jFormattedTextFieldTelVendedor.setText(String.valueOf(fornecedores.getTelefonevendedor()));
                    jTextFieldEmail.setText(fornecedores.getEmail());
                    jTextFieldCNPJ.setText(fornecedores.getCnpj());
                    //jTextFieldInscricaoEstadual.setText(fornecedores.getInscricaoestadual());
                    jTextFieldObservacao.setText(fornecedores.getObservacao());
                    jTextFieldDataCadastro.setText(sfd.format(fornecedores.getDatacadastro()));

                    //tableResultado.addRow(new Object[] {orca.getCodorcamentos(), sfd.format(orca.getDatacadastro())});

                }

                if (listFornecedores.isEmpty()) {
                    LimpaCampos();
                    jLabelRetorno.setText("Fornecedor não encontrado!!");
                    jTextFieldPesqFornecedor.requestFocus();
                    return ;
                }

        }
                transacao.commit();
                sessao.close();
            
    }//GEN-LAST:event_jTextFieldPesqFornecedorKeyReleased

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        jTextFieldPesqFornecedor.setEditable(true);
        jTextFieldPesqVendedor.setEditable(true);
        jButtonAlterar.setEnabled(true);
        jButtonDeletar.setEnabled(true);
        jButtonSalvar.setEnabled(false);
        //jButtonLimpar.setEnabled(true);
        //jComboBoxGrupo.setEditable(true);
        jTextFieldPesqFornecedor.requestFocus();
        //Pesquisa();
        if(jButtonNovo.getText().equals("Cancelar")){
            jButtonNovo.setText("Incluir");
            LimpaCampos();

            //jComboBoxGrupo.setEditable(true);
        }

        if(jButtonAlterar.getText().equals("Cancelar")){
            jButtonAlterar.setText("Alterar");
        }

        if(jButtonPesquisar.getText().equals("Cancelar")){
            jButtonPesquisar.setText("Pesquisar");
            jTextFieldPesqFornecedor.setEditable(false);
            jTextFieldPesqVendedor.setEditable(false);
            jTextFieldPesqFornecedor.setText("");
            jTextFieldPesqVendedor.setText("");
            jButtonAlterar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            //jButtonLimpar.setEnabled(false);
            jTextFieldPesqFornecedor.requestFocus();
            LimpaCampos();
            //jComboBoxGrupo.setEditable(true);
        }else{
            jButtonPesquisar.setText("Cancelar");

        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldPesqVendedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesqVendedorKeyReleased
             SimpleDateFormat sfd = new SimpleDateFormat("dd/MM/yyyy");
            Session sessao = HibernateUtil.getSessionFactory().openSession();
            Transaction transacao = sessao.beginTransaction();
            
            Query queryFornecedor = sessao.createQuery(" from Fornecedores as f where f.vendedor like '"+jTextFieldPesqVendedor.getText().toUpperCase()+"%'  order by f.fornecedor");

            //Query consultaMat = sessao.createQuery("from MateriaisOrcamentos as mo where mo.codorcamentos = '"+jListOrcamento.getSelectedValue().toString()+"'");
            List listFornecedores = queryFornecedor.list();
            //List materiais = consultaMat.list();
            //System.out.println("foram encontradas "+orcamentos.size()+" orcamentos");
            Iterator i = listFornecedores.iterator();

            Fornecedores fornecedores = null;
           // javax.swing.table.DefaultTableModel tableResultado =(javax.swing.table.DefaultTableModel)jTableHistoricoOrcamento.getModel();
            //tableResultado.setRowCount(0);
            //MateriaisOrcamentos matOrca = new MateriaisOrcamentos();
            //System.out.println("MAT ->"+ matOrca.getProduto());
            if(jTextFieldPesqVendedor.getText().equals("")){
                //Consulta = false;
                LimpaCampos();
                jTextFieldPesqVendedor.requestFocus();
            }else{
                while (i.hasNext()) {

                     fornecedores = (Fornecedores) i.next();
                    

                    jTextFieldCodigo.setText(String.valueOf(fornecedores.getCodfornecedor()));
                    jTextFieldRazaoSocial.setText(fornecedores.getFornecedor());
                    jTextFieldVendedor.setText(fornecedores.getVendedor());
                    jTextFieldEndereco.setText(fornecedores.getEndereco());
                    jTextFieldBairro.setText(fornecedores.getBairro());
                    jTextFieldCidade.setText(fornecedores.getCidade());
                    jFormattedTextFieldCep.setText(fornecedores.getCep());
                    jFormattedTextFieldTelefone.setText(fornecedores.getTelefone());
                    jFormattedTextFieldCelular.setText(fornecedores.getCelular());
                    jFormattedTextFieldTelVendedor.setText(String.valueOf(fornecedores.getTelefonevendedor()));
                    jTextFieldEmail.setText(fornecedores.getEmail());
                    jTextFieldCNPJ.setText(fornecedores.getCnpj());
                    //jTextFieldInscricaoEstadual.setText(fornecedores.getInscricaoestadual());
                    jTextFieldObservacao.setText(fornecedores.getObservacao());
                    jTextFieldDataCadastro.setText(sfd.format(fornecedores.getDatacadastro()));

                    //tableResultado.addRow(new Object[] {orca.getCodorcamentos(), orca.getDatacadastro()});

                }

                if (listFornecedores.isEmpty()) {
                    LimpaCampos();
                    jLabelRetorno.setText("Fornecedor não encontrado!!");
                    jTextFieldPesqVendedor.requestFocus();
                    return ;
                }
        }
                transacao.commit();
                sessao.close();
            
    }//GEN-LAST:event_jTextFieldPesqVendedorKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        LimpaCampos();
        jTextFieldCodigo.setText("");
        jTextFieldDataCadastro.setText("");
        System.out.println("Abrindo Tela Cadastro Fornecedores... - Opened");
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        LimpaCampos();
        jTextFieldCodigo.setText("");
        jTextFieldDataCadastro.setText("");
        jButtonSalvar.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        System.out.println("Fechando Tela Cadastro Fornecedores... - Closed");
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelVendedor;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRetorno;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCNPJ;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldInscricaoEstadual;
    private javax.swing.JTextField jTextFieldObservacao;
    private javax.swing.JTextField jTextFieldPesqFornecedor;
    private javax.swing.JTextField jTextFieldPesqVendedor;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    private javax.swing.JTextField jTextFieldVendedor;
    // End of variables declaration//GEN-END:variables

}
