/*
 * EscolhaDir.java
 *
 * Created on 18 de Dezembro de 2008, 10:58
 */

package Tela;

import Util.UIManagerPut;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author  Administrador
 */
public class Diretorio extends javax.swing.JInternalFrame {
    public static String dir;
    /** Creates new form EscolhaDir */
    public Diretorio(String titulo) {
        initComponents();
        
        UIManagerPut put = new UIManagerPut();
        put.CsUIManagerPut();
        
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.setCurrentDirectory(new File("C:\\"));
        jFileChooser1.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.setApproveButtonText("Selecionar Pasta");
        jFileChooser1.setDialogTitle(titulo);
        //FileNameExtensionFilter filter = new FileNameExtensionFilter("Apenas pastas");
        //jFileChooser1.setFileFilter(filter);
        jFileChooser1.setMultiSelectionEnabled(false);
        if(jFileChooser1.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
            File getDir =jFileChooser1.getSelectedFile();
            String dir = getDir.toString();
            Diretorio.dir = dir+"\\";
        }else{
            dir = "";
        }
        
    }

    public void setDir(String titulo){
        JFileChooser jFileChooser1 = new JFileChooser();
        jFileChooser1.setFileSelectionMode(jFileChooser1.DIRECTORIES_ONLY);
        jFileChooser1.setApproveButtonText("Selecionar Pasta");
        jFileChooser1.setDialogTitle(titulo);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "jpg", "gif");
        jFileChooser1.setFileFilter(filter);
        jFileChooser1.setMultiSelectionEnabled(false);
        if(jFileChooser1.showOpenDialog(this) == jFileChooser1.APPROVE_OPTION){
            File getDir =jFileChooser1.getSelectedFile();
            String dir = getDir.toString();
            this.dir = dir;
        }
    }
    /*
    public void setDir(String titulo){
        JFileChooser diretorio = new JFileChooser(); //Setanto uma variavel para o o methodo...........
        diretorio.setFileSelectionMode(diretorio.DIRECTORIES_ONLY); //setanto o parametro apos a criação da varial "Isso e importante"
        diretorio.setApproveButtonText("Selecionar Pasta");
        diretorio.setDialogTitle(titulo);
        diretorio.setMultiSelectionEnabled(false);
        int Retorno = diretorio.showOpenDialog(diretorio); //varial Inteiro para chamada
        
        if(Retorno == JFileChooser.APPROVE_OPTION) {
           JOptionPane.showMessageDialog(null,"Este é o local: " +
                   diretorio.getSelectedFile().getName(),"Lista files",JOptionPane.INFORMATION_MESSAGE);
           //File getDir =jFileChooser1.getSelectedFile();
           //String dir = getDir.toString();
           //this.dir = dir;
        }
    }
    */
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
