/*
 * RelatorioHistoricoEntradaSaida.java
 *
 * Created on 14 de Setembro de 2009, 01:14
 */

package Tela;

import Util.CalendarComboBox;
import Util.HibernateUtil;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.Copies;
import javax.print.attribute.standard.JobName;
import javax.print.attribute.standard.MediaSizeName;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author  Administrador
 */

public class RelatorioHistoricoEntradaSaida extends javax.swing.JInternalFrame {
    private int contador;
    private static RelatorioHistoricoEntradaSaida relatorioVendaPeriodo;
    private Inicial inicial = null;
    static private int progresso;
    static private int total;
    
    public static RelatorioHistoricoEntradaSaida getInstance(Inicial instancia) throws PropertyVetoException, SQLException, ClassNotFoundException {
        if(relatorioVendaPeriodo == null)
            relatorioVendaPeriodo = new RelatorioHistoricoEntradaSaida(instancia);
        return relatorioVendaPeriodo;
    }
    private int ordem;
    
    /** Creates new form CadGrupos */
   

     public RelatorioHistoricoEntradaSaida(Inicial instancia) throws SQLException, ClassNotFoundException {
        initComponents();
        this.setIconifiable(true);
        this.setClosable(true);
        

        Dimension centraliza = Toolkit.getDefaultToolkit().getScreenSize();   
        this.setLocation((centraliza.width-this.getSize().width)/2,   
                      (centraliza.height-this.getSize().height)/2);
        
        
        setFrameIcon(new ImageIcon(this.getClass().getClassLoader().getResource("imagens/IconeLN.png")));
       
        jRadioButtonDescricao2.setSelected(true);
        
    }

     
     public static String getDataTelaToBD(String x) {
        java.lang.String dia, mes, ano = "";
        java.lang.String data = "";
        dia = x.substring(0,2);
       //System.out.println("DIA " + dia);
        mes = x.substring(3,5);
        ano = x.substring(6, 10);
        data = ano +"-"+ mes + "-" + dia;
        //System.out.println("D  " + data );
        return data;
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOrdenar = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxDataInicial = new CalendarComboBox(true);
        jComboBoxDataFinal = new CalendarComboBox(true);
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonProduto2 = new javax.swing.JRadioButton();
        jRadioButtonDescricao2 = new javax.swing.JRadioButton();
        jRadioButtonData2 = new javax.swing.JRadioButton();
        jButtonVisual = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("RELATÓRIO DE VENDAS POR PERÍODO");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RELATÓRIO DE VENDAS POR PERÍODO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("DATA INICIAL:");

        jLabel2.setText("DATA FINAL:");

        jComboBoxDataInicial.setSelectedItem(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        jComboBoxDataInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxDataInicialKeyPressed(evt);
            }
        });

        jComboBoxDataFinal.setSelectedItem(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("ORDENAR RELATÓRIO POR"));

        buttonGroupOrdenar.add(jRadioButtonProduto2);
        jRadioButtonProduto2.setMnemonic('M');
        jRadioButtonProduto2.setText("MATERIAL");
        jRadioButtonProduto2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonProdutoStateChanged(evt);
            }
        });

        buttonGroupOrdenar.add(jRadioButtonDescricao2);
        jRadioButtonDescricao2.setMnemonic('E');
        jRadioButtonDescricao2.setText("DESCRIÇÃO");

        buttonGroupOrdenar.add(jRadioButtonData2);
        jRadioButtonData2.setMnemonic('D');
        jRadioButtonData2.setText("DATA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonProduto2)
                .addGap(65, 65, 65))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonDescricao2)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonData2)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jRadioButtonProduto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDescricao2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonData2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonVisual.setFont(new java.awt.Font("Arial", 1, 12));
        jButtonVisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visualizar - Cópia.png"))); // NOI18N
        jButtonVisual.setMnemonic('V');
        jButtonVisual.setText("Visualizar");
        jButtonVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Arial", 1, 12));
        jButtonSair.setMnemonic('S');
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TODOS", "ENTRADA", "SAÍDA" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonVisual)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSair))
                            .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVisual)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
doDefaultCloseAction();
}//GEN-LAST:event_jButtonSairActionPerformed

private void jButtonVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualActionPerformed
        try {
            jComboBoxDataInicial.requestFocus();
            if (jRadioButtonProduto2.isSelected()) {
                ordem = 2;
            } else if (jRadioButtonData2.isSelected()) {
                ordem = 6;
            } else if (jRadioButtonDescricao2.isSelected()) {
                ordem = 3;
            } else {
                ordem = 2;
            }
            if (jComboBoxDataInicial.getSelectedItem() == null || jComboBoxDataFinal.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Selecione as datas de pesquisa", "Atenção", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("ENTROU NO IF ");
            }
            //try{
            Map parametros = new HashMap();
            Statement st = null;
            ResultSet rs = null;
            StringBuffer sql = new StringBuffer();
            sql.delete(0, sql.length());
            JasperReport rela = (JasperReport) JRLoader.loadObject(this.getClass().getClassLoader().getResource("Relatorio/HistoricoEntradaSaida.jasper"));

            System.out.println("CAMINHO: "+ new String(JRLoader.getResource("Relatorio/HistoricoEntradaSaida.jasper").toString()));
            System.out.println("CAMINHO: "+ rela.getLanguage());
            System.out.println("CAMINHO: "+ rela.getQuery());
            System.out.println("CAMINHO: "+ rela.getName());
            System.out.println("CAMINHO: "+ rela.getCompilerClass());

            //URL relatorio = getClass().getClassLoader().getResource("relatorio/VendasPeriodo.jasper");

            String dataInicial = jComboBoxDataInicial.getSelectedItem().toString();
            String dataFinal = jComboBoxDataFinal.getSelectedItem().toString();
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date dataI = new java.sql.Date(format.parse(dataInicial).getTime());
            java.sql.Date dataF = new java.sql.Date(format.parse(dataInicial).getTime());
            System.out.println("PARAM " + dataInicial + dataFinal + " ordem " + ordem);
            //parametros.put("datainicial",getDataTelaToBD(dataInicial));
            //parametros.put("datafinal", getDataTelaToBD(dataFinal));
            parametros.put("datainicial", dataInicial);
            parametros.put("datafinal", dataFinal);
            parametros.put("order", ordem);
            parametros.put("dadosPedidos", rela);
            //sql.append(" select datainicial, datafinal,codigo, apelido, unid as unidade,SUM(qtdexames)::bigint as qtdexames, TRUNC(SUM(totalexames),2) as totalexames1,SUM(qtdpedido)::bigint as qtdpedido,SUM(qtdpaciente)::bigint as qtdpaciente, mes, ");
            //sql.append("SELECT *, grupos.idgrupo AS grupo_idgrupo, grupos.grupo AS grupos_grupo FROM grupos");
            //sql.append("SELECT vendas.produto AS vendas_produto, vendas.descricao AS vendas_descricao, vendas.qtd AS vendas_qtd, vendas.total AS vendas_total, vendas.tipovenda AS vendas_tipovenda, vendas.data AS vendas_data, vendas.unitario AS vendas_unitario FROM vendas vendas WHERE DATA BETWEEN '" + getDataTelaToBD(dataInicial) + "' AND '" + getDataTelaToBD(dataFinal) + "' ORDER BY "+ ordem);
            sql.append("SELECT vendas.produto AS vendas_produto, vendas.descricao AS vendas_descricao, ");
            sql.append("vendas.qtd AS vendas_qtd, ");
            sql.append("vendas.total AS vendas_total, vendas.tipovenda AS vendas_tipovenda, ");
            sql.append("vendas.data AS vendas_data, vendas.unitario AS vendas_unitario ");
            sql.append("FROM vendas vendas ");
            sql.append("WHERE DATA BETWEEN '" + getDataTelaToBD(dataInicial) + "' AND '" + getDataTelaToBD(dataFinal) + "' ORDER BY " + ordem);
            //parametros.put("num1",1);
            //parametros.put("num2", 20);
            //parametros.put("dadosPedidos", rela);
            System.out.println("SQL = " + sql.toString().toLowerCase());
            String query = sql.toString().toUpperCase();
            System.out.println("QUERY = " + query);
            System.out.println("PARAM " + dataInicial);

//            Connection conn;
//            conn = ConectaBD.getConnection();
//            st = conn.createStatement();
//            rs = st.executeQuery(query);

            SimpleDateFormat sfd2 = new SimpleDateFormat("dd/MM/yyyy");
            String data = sfd2.format(new Date());

            Session sessao = HibernateUtil.getSessionFactory().openSession();// fabricaDeSessoes.openSession();
            Transaction transacao = sessao.beginTransaction();

            Query materiais = null;

            if(jComboBoxTipo.getSelectedItem().toString().equals("TODOS")){
                materiais = sessao.createQuery("from HistoricoEntrada h where h.dataentrada between '"+dataInicial+"' and '"+dataFinal+"' and h.status in ('E', 'S') order by "+ ordem);
                System.out.println("Tipo: TODOS");
            }else if(jComboBoxTipo.getSelectedItem().toString().equals("ENTRADA")){
                materiais = sessao.createQuery("from HistoricoEntrada h where h.dataentrada between '"+dataInicial+"' and '"+dataFinal+"' and h.status = 'E' order by "+ ordem);
                System.out.println("Tipo: ENTRADA");
            }else if(jComboBoxTipo.getSelectedItem().toString().equals("SAÍDA")) {
                materiais = sessao.createQuery("from HistoricoEntrada h where h.dataentrada between '"+dataInicial+"' and '"+dataFinal+"' and h.status = 'S' order by "+ ordem);
                System.out.println("Tipo: SAIDA");
            }

            //Query consultaMat = sessao.createQuery("from MateriaisOrcamentos as mo where mo.codorcamentos = '"+jListOrcamento.getSelectedValue().toString()+"'");
            List listHistorico = materiais.list();
            //List materiais = consultaMat.list();
            //System.out.println("foram encontradas "+orcamentos.size()+" orcamentos");
            Iterator iHistorico = listHistorico.iterator();

            String printer = "hp6";
            
            System.out.println("printer === " + printer);
//            PrintServiceAttributeSet servAttSet = new HashPrintServiceAttributeSet();
//            servAttSet.add(new PrinterName(printer, null)); //comentei porque por enquanto esta abrindo o dialog.
//            JRBeanCollectionDataSource list = new JRBeanCollectionDataSource(listHistorico);
//            //JRResultSetDataSource jrResultSetDataSource = new JRResultSetDataSource(rs);
//
//            JasperPrint impressao = JasperManager.fillReport(rela, parametros, list);


            JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(listHistorico);
        //JasperReport jasperReport = JasperManager.loadReport(JRLoader.loadObject(this.getClass().getClassLoader().getResource("Relatorio/HistoricoEntradaSaida.jasper")));
        JasperPrint jasperPrint = JasperFillManager.fillReport(rela,parametros, ds);



            //configura a impressora
            PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();
            aset.add(OrientationRequested.LANDSCAPE);
            aset.add(MediaSizeName.ISO_A4);
            aset.add(new Copies(1)); //numero de copias
            aset.add(new JobName("dadosPedidos", null));


            JasperViewer jrviewer = new JasperViewer(jasperPrint, false);
            jrviewer.setTitle("RELATÓRIO DE ENTRADA E SAIDA DE MATERIAIS POR PERÍODO");
            ImageIcon icone = new ImageIcon(this.getClass().getClassLoader().getResource("imagens/IconeLN.png"));
            jrviewer.setIconImage(icone.getImage());
            jrviewer.setExtendedState(JFrame.MAXIMIZED_BOTH);
            jrviewer.setDefaultCloseOperation(JasperViewer.DISPOSE_ON_CLOSE);
            jrviewer.setVisible(true);
            jrviewer.transferFocus();

            
        } catch (Exception ex) {

            Logger.getLogger(Inicial.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"Erro ao gerar relatório" + "\n" + ex.getMessage(), "Atenção", JOptionPane.INFORMATION_MESSAGE );
        }
//        } catch (Exception ex) {
//
//            Logger.getLogger(RelatorioComprasPeriodo.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null,"Erro ao gerar relatório." + "\n" + ex.toString(), "Atenção", JOptionPane.ERROR_MESSAGE );
//        }

            
    


                 
}//GEN-LAST:event_jButtonVisualActionPerformed

  public class Progress extends JDialog{// JInternalFrame {
    public Progress() {
        this.setTitle("Aguarde...");

        this.setSize(200, 25);
        this.toFront();
        setModal(false);
        JProgressBar progress = new JProgressBar();
        progress.setIndeterminate(true);
        progress.setSize(100,20);
        progress.setString("Aguarde...");

        getContentPane().add(progress);
        pack();
        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((tela.width - this.getSize().width) / 2,
             (tela.height - this.getSize().height) / 2);
    }
            
} 

private void jRadioButtonProdutoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonProdutoStateChanged
// TODO add your handling code here:
}//GEN-LAST:event_jRadioButtonProdutoStateChanged

private void jComboBoxDataInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxDataInicialKeyPressed
if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
        System.out.println("ENTER");
       jButtonVisual.requestFocus();
    }
}//GEN-LAST:event_jComboBoxDataInicialKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupOrdenar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonVisual;
    private javax.swing.JComboBox jComboBoxDataFinal;
    private javax.swing.JComboBox jComboBoxDataInicial;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonData2;
    private javax.swing.JRadioButton jRadioButtonDescricao2;
    private javax.swing.JRadioButton jRadioButtonProduto2;
    // End of variables declaration//GEN-END:variables
//*/
}
