/*
 * TelaAnalitica.java
 *
 * Created on 1 de Novembro de 2009, 23:00
 */

package Tela;


import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  LEONARDU
 */
public class TelaAnalitica extends javax.swing.JDialog {

    public static String codigo;
    public static String grupo;
    public static String descricao;
    public static String modelo;
    public static String unidade;
    public static String local;
    public static String qtdMin;
    public static String qtdMax;
    public static String qtdEstoque;
    public static String valorCompra;
    public static String valor;
    public static String promocao;
    public static String comercial;
    public static String codFor1;
    public static String codFor2;
    public static String codFor3;
    public static String forn1;
    public static String forn2;
    public static String forn3;
    public static String valor1;
    public static String valor2;
    public static String valor3;
    
            
    /** Creates new form TelaAnalitica */
    public TelaAnalitica(java.awt.Frame parent, boolean modal, String cod) throws Exception {
        super(parent, modal);
        initComponents();
        setLocation(500,400);
        
        codigo = cod;
        System.out.println(cod +""+ codigo);
        getAnalitica();
    }

    public static String moeda(double vlr){
            java.text.DecimalFormat df = new java.text.DecimalFormat("###,###,##0.00");
            return df.format( vlr );
     }
    
    public void getAnalitica() throws Exception{
//        MercadoriaVO mVO = null;
//        Mercadoria mercadoria = new Mercadoria();
//        mVO = mercadoria.obterCodAnalitica(codigo);
        
//        if(mVO!= null){
//            jLabelCodigo.setText(mVO.getCod());
//            jLabelDescricao.setText(mVO.getDescricao());
//            jLabelGrupo.setText(mVO.getGrupo());
//            jLabelModelo.setText(mVO.getModelo());
//            jLabelUnidade.setText(mVO.getUnidade());
//            jLabelLocal.setText(mVO.getLocal());
//            jLabelQtdMin.setText(String.valueOf(mVO.getQtdMin()));
//            jLabelQtdMax.setText(String.valueOf(mVO.getQtdMax()));
//            jLabelQtdEstoque.setText(String.valueOf(mVO.getQtdEstoque()));
//            jLabelValorCompra.setText(moeda(mVO.getValorCompra()));
//            jLabelValor.setText(moeda(mVO.getValor()));
//            jLabelPromocao.setText(moeda(mVO.getPromocao()));
//            jLabelComercial.setText(moeda(mVO.getComercial()));
//            jLabelCodFor1.setText(mVO.getCodfor1());
//            jLabelCodFor2.setText(mVO.getCodfor2());
//            jLabelCodFor3.setText(mVO.getCodfor3());
//            jLabelNomeFor1.setText(mVO.getFornecedor1());
//            jLabelNomeFor2.setText(mVO.getFornecedor2());
//            jLabelNomeFor3.setText(mVO.getFornecedor3());
//            jLabelValorFor1.setText(moeda(mVO.getValor1()));
//            jLabelValorFor2.setText(moeda(mVO.getValor2()));
//            jLabelValorFor3.setText(moeda(mVO.getValor3()));
//        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelGrupo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelUnidade = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelLocal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabelValorCompra = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelPromocao = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabelQtdMin = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelQtdMax = new javax.swing.JLabel();
        jLabelQtdEstoque = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabelCodFor1 = new javax.swing.JLabel();
        jLabelNomeFor1 = new javax.swing.JLabel();
        jLabelValorFor1 = new javax.swing.JLabel();
        jLabelValorFor2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabelCodFor2 = new javax.swing.JLabel();
        jLabelNomeFor2 = new javax.swing.JLabel();
        jLabelCodFor3 = new javax.swing.JLabel();
        jLabelNomeFor3 = new javax.swing.JLabel();
        jLabelValorFor3 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabelComercial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TELA ANALÍTICA");
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TELA ANALITÍCA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("CÓDIGO:");

        jLabelCodigo.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelCodigo.setForeground(java.awt.Color.white);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("GRUPO:");

        jLabelGrupo.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelGrupo.setForeground(java.awt.Color.white);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("DESCRIÇÃO:");

        jLabelDescricao.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelDescricao.setForeground(java.awt.Color.white);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("MODELO:");

        jLabelModelo.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelModelo.setForeground(java.awt.Color.white);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("UNIDADE:");

        jLabelUnidade.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelUnidade.setForeground(java.awt.Color.white);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("LOCAL:");

        jLabelLocal.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelLocal.setForeground(java.awt.Color.white);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("VALOR COMPRA:");

        jLabelValorCompra.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelValorCompra.setForeground(java.awt.Color.white);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("VALOR:");

        jLabelValor.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelValor.setForeground(java.awt.Color.white);

        jLabelPromocao.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelPromocao.setForeground(java.awt.Color.white);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("PROMOÇÃO:");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("QTD MINIMA:");

        jLabelQtdMin.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelQtdMin.setForeground(java.awt.Color.white);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("QTD MAXIMA:");

        jLabelQtdMax.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelQtdMax.setForeground(java.awt.Color.white);

        jLabelQtdEstoque.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelQtdEstoque.setForeground(java.awt.Color.white);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("QTD ESTOQUE:");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("F1:");

        jLabelCodFor1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelCodFor1.setForeground(java.awt.Color.white);

        jLabelNomeFor1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelNomeFor1.setForeground(java.awt.Color.white);

        jLabelValorFor1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelValorFor1.setForeground(java.awt.Color.white);

        jLabelValorFor2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelValorFor2.setForeground(java.awt.Color.white);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel30.setForeground(java.awt.Color.white);
        jLabel30.setText("F2:");

        jLabelCodFor2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelCodFor2.setForeground(java.awt.Color.white);

        jLabelNomeFor2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelNomeFor2.setForeground(java.awt.Color.white);

        jLabelCodFor3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelCodFor3.setForeground(java.awt.Color.white);

        jLabelNomeFor3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelNomeFor3.setForeground(java.awt.Color.white);

        jLabelValorFor3.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelValorFor3.setForeground(java.awt.Color.white);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel36.setForeground(java.awt.Color.white);
        jLabel36.setText("F3:");

        jLabel37.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel37.setForeground(java.awt.Color.white);
        jLabel37.setText("COMERCIAL:");

        jLabelComercial.setFont(new java.awt.Font("Arial", 1, 12));
        jLabelComercial.setForeground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel21)
                                            .addComponent(jLabel24))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelQtdMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelQtdEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelQtdMax, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelComercial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPromocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelValorCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGap(74, 74, 74))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCodFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNomeFor1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCodFor2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNomeFor2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelCodFor3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelNomeFor3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelValorFor3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValorFor2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelValorFor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabelModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabelLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabelQtdMin, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabelQtdMax, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabelQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabelUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabelValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabelPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(jLabelComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeFor1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addComponent(jLabelValorFor1, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCodFor1, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeFor2, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addComponent(jLabelValorFor2, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCodFor2, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeFor3, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addComponent(jLabelValorFor3, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCodFor3, javax.swing.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
    if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
       dispose();
    }
}//GEN-LAST:event_formKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    String cod = null;
                    TelaAnalitica dialog = new TelaAnalitica(new javax.swing.JFrame(), true, cod);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(TelaAnalitica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCodFor1;
    private javax.swing.JLabel jLabelCodFor2;
    private javax.swing.JLabel jLabelCodFor3;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelComercial;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JLabel jLabelLocal;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelNomeFor1;
    private javax.swing.JLabel jLabelNomeFor2;
    private javax.swing.JLabel jLabelNomeFor3;
    private javax.swing.JLabel jLabelPromocao;
    private javax.swing.JLabel jLabelQtdEstoque;
    private javax.swing.JLabel jLabelQtdMax;
    private javax.swing.JLabel jLabelQtdMin;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JLabel jLabelValorCompra;
    private javax.swing.JLabel jLabelValorFor1;
    private javax.swing.JLabel jLabelValorFor2;
    private javax.swing.JLabel jLabelValorFor3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
